import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Link } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, Download, FileText, Presentation, Code, FileJson, Trash2, Clock, Search, Bot, Package, Filter } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { Gift, Agent } from "@shared/schema";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

const typeIcons: Record<string, typeof FileText> = {
  pdf: FileText,
  slides: Presentation,
  document: FileText,
  code: Code,
  data: FileJson,
};

const typeLabels: Record<string, string> = {
  pdf: "PDF Document",
  slides: "Presentation",
  document: "Research Brief",
  code: "Code Package",
  data: "Data Export",
};

const statusColors: Record<string, string> = {
  generating: "bg-yellow-500/10 text-yellow-600",
  ready: "bg-green-500/10 text-green-600",
  failed: "bg-red-500/10 text-red-600",
};

export default function Gifts() {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedType, setSelectedType] = useState<string>("all");

  const { data: gifts, isLoading: loadingGifts } = useQuery<Gift[]>({
    queryKey: ["/api/gifts"],
  });

  const { data: agents } = useQuery<Agent[]>({
    queryKey: ["/api/agents"],
  });

  const agentMap = new Map<string, Agent>();
  agents?.forEach(a => agentMap.set(a.id, a));

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/gifts/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/gifts"] });
      toast({ title: "Gift deleted" });
    },
    onError: () => {
      toast({ title: "Failed to delete gift", variant: "destructive" });
    },
  });

  const handleDownload = async (gift: Gift) => {
    try {
      const response = await fetch(`/api/gifts/${gift.id}/download`, {
        credentials: 'include',
      });
      if (!response.ok) throw new Error("Download failed");
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = gift.fileName || `${gift.title}.${gift.type}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({ title: "Download started" });
    } catch (error) {
      toast({ title: "Download failed", variant: "destructive" });
    }
  };

  const filteredGifts = gifts?.filter(g => {
    const matchesSearch = !searchQuery || 
      g.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      g.description?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      g.tags?.some(t => t.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesType = selectedType === "all" || g.type === selectedType;
    return matchesSearch && matchesType;
  });

  const readyCount = gifts?.filter(g => g.status === "ready").length || 0;
  const generatingCount = gifts?.filter(g => g.status === "generating").length || 0;
  const autoGenCount = gifts?.filter(g => g.tags?.includes("auto-generated")).length || 0;

  if (loadingGifts) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <Skeleton className="h-8 w-32" />
          <Skeleton className="h-9 w-28" />
        </div>
        <div className="grid gap-4 md:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <Skeleton key={i} className="h-24" />
          ))}
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {[1, 2, 3].map((i) => (
            <Skeleton key={i} className="h-48" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold" data-testid="text-gifts-title">Gifts & Deliverables</h1>
          <p className="text-muted-foreground">Research briefs, reports, presentations, and code packages generated by your agents</p>
        </div>
        <Button asChild data-testid="button-create-gift">
          <Link href="/gifts/new">
            <Plus className="h-4 w-4 mr-2" />
            Create Gift
          </Link>
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between gap-1 pb-2">
            <CardTitle className="text-sm font-medium">Ready to Download</CardTitle>
            <Download className="h-4 w-4 text-green-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{readyCount}</div>
            <p className="text-xs text-muted-foreground">Completed deliverables</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between gap-1 pb-2">
            <CardTitle className="text-sm font-medium">Auto-Generated</CardTitle>
            <Bot className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{autoGenCount}</div>
            <p className="text-xs text-muted-foreground">Created by factory agents</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between gap-1 pb-2">
            <CardTitle className="text-sm font-medium">In Progress</CardTitle>
            <Clock className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{generatingCount}</div>
            <p className="text-xs text-muted-foreground">Currently generating</p>
          </CardContent>
        </Card>
      </div>

      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search gifts by title, description, or tag..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9"
            data-testid="input-search-gifts"
          />
        </div>
        <Tabs value={selectedType} onValueChange={setSelectedType}>
          <TabsList>
            <TabsTrigger value="all" data-testid="tab-all">All</TabsTrigger>
            <TabsTrigger value="pdf" data-testid="tab-pdf">PDFs</TabsTrigger>
            <TabsTrigger value="document" data-testid="tab-document">Briefs</TabsTrigger>
            <TabsTrigger value="slides" data-testid="tab-slides">Slides</TabsTrigger>
            <TabsTrigger value="code" data-testid="tab-code">Code</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {!filteredGifts || filteredGifts.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Package className="h-12 w-12 text-muted-foreground/50 mb-4" />
            <h3 className="text-lg font-medium mb-1">
              {gifts && gifts.length > 0 ? "No matching gifts" : "No gifts yet"}
            </h3>
            <p className="text-sm text-muted-foreground mb-4 text-center max-w-md">
              {gifts && gifts.length > 0 
                ? "Try adjusting your search or filter criteria"
                : "Start the factory to have agents automatically generate research briefs, reports, and deliverables. You can also create custom gifts manually."}
            </p>
            {(!gifts || gifts.length === 0) && (
              <div className="flex gap-2">
                <Button asChild>
                  <Link href="/gifts/new">
                    <Plus className="h-4 w-4 mr-2" />
                    Create Gift
                  </Link>
                </Button>
                <Button variant="outline" asChild>
                  <Link href="/factory">
                    <Bot className="h-4 w-4 mr-2" />
                    Go to Factory
                  </Link>
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {filteredGifts.map((gift) => {
            const Icon = typeIcons[gift.type] || FileText;
            const agent = gift.agentId ? agentMap.get(gift.agentId) : undefined;
            return (
              <Card key={gift.id} data-testid={`card-gift-${gift.id}`}>
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2 min-w-0">
                      <div className="p-2 rounded-md bg-primary/10 shrink-0">
                        <Icon className="h-4 w-4 text-primary" />
                      </div>
                      <div className="min-w-0">
                        <CardTitle className="text-base truncate">{gift.title}</CardTitle>
                        <CardDescription className="text-xs">
                          {typeLabels[gift.type] || gift.type.toUpperCase()}
                        </CardDescription>
                      </div>
                    </div>
                    <Badge className={statusColors[gift.status] || ""}>
                      {gift.status === "generating" && <Clock className="h-3 w-3 mr-1" />}
                      {gift.status}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  {gift.description && (
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      {gift.description}
                    </p>
                  )}

                  {agent && (
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                      <Bot className="h-3.5 w-3.5" />
                      <span>Created by {agent.name}</span>
                      {agent.provider && (
                        <Badge variant="outline" className="text-xs">{agent.provider}</Badge>
                      )}
                    </div>
                  )}
                  
                  {gift.tags && gift.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      {gift.tags.slice(0, 4).map((tag) => (
                        <Badge key={tag} variant="outline" className="text-xs">
                          {tag}
                        </Badge>
                      ))}
                      {gift.tags.length > 4 && (
                        <Badge variant="outline" className="text-xs">
                          +{gift.tags.length - 4}
                        </Badge>
                      )}
                    </div>
                  )}

                  <div className="flex items-center justify-between pt-2 border-t">
                    <span className="text-xs text-muted-foreground">
                      {gift.createdAt && new Date(gift.createdAt).toLocaleDateString()}
                    </span>
                    <div className="flex gap-1">
                      {gift.status === "ready" && (
                        <Button 
                          size="icon" 
                          variant="ghost"
                          onClick={() => handleDownload(gift)}
                          data-testid={`button-download-${gift.id}`}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                      )}
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button 
                            size="icon" 
                            variant="ghost"
                            data-testid={`button-delete-${gift.id}`}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Delete gift?</AlertDialogTitle>
                            <AlertDialogDescription>
                              This will permanently delete "{gift.title}". This action cannot be undone.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => deleteMutation.mutate(gift.id)}
                            >
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
